source 'https://rubygems.org'
gem 'rails', '~> 4.2'
gem 'rails-i18n' 
gem 'responders', '~> 2.0'
gem "better_errors", "~> 2.5.1"
gem 'mysql2'
gem 'rake', '~> 13.0'
gem 'figaro' 
gem 'foreman'
# masum

gem 'applescript', '~> 1.0'
gem 'ovirt-engine-sdk', '~> 4.3'
gem 'dotenv-rails', groups: [:development, :test]
gem 'peatio'
gem 'google-protobuf'
gem "passenger", ">= 5.3.2", require: "phusion_passenger/rack_handler"
gem "bundler", ">= 1.17.3" 
gem 'jbuilder'
gem 'rdoc'
gem 'webconsole' if RUBY_PLATFORM.match?(/darwin/)
gem 'ruby'
gem 'bcrypt', '~> 3.1', '>= 3.1.10'
gem 'bcrypt-ruby' 
gem 'rubysl-shellwords', '~> 2.0'
gem 'sprockets', '~> 4.0.0'
gem 'osaka', '~> 0.4.13'
gem 'nokogiri'
gem 'rack'
gem 'rspec'
gem 'io-console'
gem 'puma'
gem 'redis-rails', '~> 5.0.2'
gem 'rotp', '3.3.1'
gem 'json'
gem 'webconsole', '~> 0.2.1'
gem 'padrino'
gem 'omniauth',               '~> 1.8.1'
gem 'omniauth-identity', '~> 1.1', '>= 1.1.1'
gem 'omniauth-auth0',         '~> 2.0.0'
gem 'omniauth-google-oauth2', '~> 0.5.2'
gem 'omniauth-facebook'
gem 'rucaptcha'
gem 'dalli'
gem 'hashie', '~> 3.0'
gem 'aasm', '~> 3.4.0'
gem 'amqp', '~> 1.8'
gem 'bunny', '~> 2.12'
gem 'cancancan'
gem 'enumerize'
gem 'datagrid'
gem 'kaminari'
gem 'paranoid2'
gem 'active_hash'
gem 'http_accept_language'
gem 'paper_trail', '~> 3.0.1'
gem 'rails-observers'
gem 'country_select', '~> 2.1.0'
gem 'gon', '~> 5.2.0'
gem 'pusher'
gem 'eventmachine', '~> 1.0.4'
gem 'em-websocket', '~> 0.5.1'
gem 'simple_form', '~> 3.1.0'
gem 'slim-rails'
gem 'sass-rails' 
gem 'coffee-rails'
gem 'uglifier', '~> 4.1'
gem 'jquery-rails'
gem 'angularjs-rails', '~> 1.3.15'
gem 'bootstrap-sass', '~> 3.4.1'
gem 'font-awesome-sass'
gem 'font-awesome-rails'
gem 'bourbon'
gem 'momentjs-rails'
gem 'eco'
gem 'browser', '~> 0.8.0'
gem 'rbtree'
gem 'liability-proof', '0.0.9'
gem 'grape', '~> 1.0.1'
gem 'grape-entity', '~> 0.5.2'
gem 'grape-swagger', '~> 0.27.3'
gem 'grape-swagger-ui', '~> 2.2.8'
gem 'rack-attack', '~> 3.0.0'
gem 'easy_table'
gem 'carrierwave', '~> 1.3', '>= 1.3.2'
gem 'fog'
gem "rest-client", ">= 1.8.0"
gem 'jwt', '~> 1.5'
gem 'email_validator', '~> 1.6'
gem 'clipboard-rails', '~> 1.7'
gem 'mini_racer', '~> 0.1', require: false
gem 'arel-is-blank', '~> 1.0'
gem 'sentry-raven', '~> 2.7', require: false
gem 'memoist', '~> 0.16'
gem 'method-not-implemented', '~> 1.0'
gem 'cryptice-passgen', '~> 0.1.2'
gem 'cashaddress'
gem 'recaptcha', require: 'recaptcha/rails'
gem 'active_model_otp'
gem 'rqrcode'
gem 'sendgrid'
gem 'phony_rails'
gem 'twilio-ruby'
gem 'bootstrap-datepicker-rails'
gem 'simplebar-rails'
gem 'validates_zipcode'
gem 'chosen-rails'
gem 'httparty'
gem 'fusioncharts-rails', '~> 0.0.2'
gem 'ajax-datatables-rails'
gem 'jquery-datatables'
gem 'useragent'
gem 'geocoder'
gem 'social-share-button', '~> 1.2'
gem 'modernizr-rails'
gem  'grpc'
group :development, :test do
  gem 'factory_bot_rails'
  gem 'faker', '~> 1.4.3'
  gem 'binding_of_caller'
  gem 'quiet_assets'
  gem 'timecop'
  gem 'rspec-rails'
  gem 'pry-byebug'
  gem 'rubocop', '~> 0.58.2', require: false
  gem 'rubocop-rspec'
end

group :test do
  gem 'database_cleaner'
  gem 'mocha', require: false

  gem 'capybara',            '~> 2.17'
  gem 'selenium-webdriver',  '~> 3.8'
  gem 'chromedriver-helper', '~> 1.1'
  gem 'rack_session_access', '~> 0.1'
end

group :development do
  gem 'capistrano',         require: false
  gem 'capistrano-rvm',     require: false
  gem 'capistrano-rails',   require: false
  gem 'capistrano-bundler', require: false
end

